Comment  `column-statistics` in `my.cnf`
selim13/docker-automysqlbackup pull request #18
Opened 2020-09-14 14:40 UTC by guillaume-gambs

Comment  `column-statistics` in `my.cnf`  because in mysql 5.7 it generate an error :
```
mysqldump: [ERROR] unknown variable 'column-statistics=0'
```

2020-09-14 19:01 UTC, selim13 requested changes

2020-09-14 19:01 UTC, selim13 commented on my.cnf
> +# column-statistics=0
Can you update the PR to completely remove the option instead of commenting it out?

2020-09-15 07:16 UTC, guillaume-gambs commented on my.cnf
> +# column-statistics=0
I remove the file and the copy from dockerfile.

2020-09-15 09:24 UTC, merged

2020-09-15 09:26 UTC, selim13 commented
Thanks!

2020-09-15 11:04 UTC, guillaume-gambs commented
> Thanks!

Thanks to you ;)